// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package queries

import (
	"context"

	"github.com/moroz/go-altcha-video/internal/dbtypes"
)

const checkUsedAltchaChallenge = `-- name: CheckUsedAltchaChallenge :one
select cast(exists (select 1 from used_altcha_challenges where challenge_hash = ?) as bool)
`

func (q *Queries) CheckUsedAltchaChallenge(ctx context.Context, challengeHash []byte) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsedAltchaChallenge, challengeHash)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertUsedAltchaChallenge = `-- name: InsertUsedAltchaChallenge :one
insert into used_altcha_challenges (challenge_hash, expires_at)
values (?, ?) returning id, challenge_hash, expires_at, created_at
`

type InsertUsedAltchaChallengeParams struct {
	ChallengeHash []byte
	ExpiresAt     dbtypes.UnixTimestamp
}

func (q *Queries) InsertUsedAltchaChallenge(ctx context.Context, arg InsertUsedAltchaChallengeParams) (*UsedAltchaChallenge, error) {
	row := q.db.QueryRowContext(ctx, insertUsedAltchaChallenge, arg.ChallengeHash, arg.ExpiresAt)
	var i UsedAltchaChallenge
	err := row.Scan(
		&i.ID,
		&i.ChallengeHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const vacuumUsedAltchaChallenges = `-- name: VacuumUsedAltchaChallenges :exec
delete from used_altcha_challenges where expires_at < unixepoch()
`

func (q *Queries) VacuumUsedAltchaChallenges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, vacuumUsedAltchaChallenges)
	return err
}
