// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getCommentCountsForPosts = `-- name: GetCommentCountsForPosts :many
select c.post_id, count(c.id) from comments c group by 1
`

type GetCommentCountsForPostsRow struct {
	PostID uuid.UUID
	Count  int64
}

func (q *Queries) GetCommentCountsForPosts(ctx context.Context) ([]*GetCommentCountsForPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentCountsForPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetCommentCountsForPostsRow
	for rows.Next() {
		var i GetCommentCountsForPostsRow
		if err := rows.Scan(&i.PostID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByPostId = `-- name: GetCommentsByPostId :many
select id, post_id, body, signature, website, created_at, updated_at from comments where post_id = ? order by id desc
`

func (q *Queries) GetCommentsByPostId(ctx context.Context, postID uuid.UUID) ([]*Comment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Body,
			&i.Signature,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertComment = `-- name: InsertComment :one
insert into comments (id, post_id, signature, body, website)
values (?, ?, ?, ?, ?)
returning id, post_id, body, signature, website, created_at, updated_at
`

type InsertCommentParams struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	Signature string
	Body      string
	Website   *string
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (*Comment, error) {
	row := q.db.QueryRowContext(ctx, insertComment,
		arg.ID,
		arg.PostID,
		arg.Signature,
		arg.Body,
		arg.Website,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Body,
		&i.Signature,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
