// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

type Comment struct {
	ID        int64
	PostID    int64
	Body      string
	Signature string
	Website   *string
	CreatedAt int64
	UpdatedAt int64
}

type Post struct {
	ID          int64
	Title       string
	Body        string
	Slug        string
	PublishedAt *int64
	CreatedAt   int64
	UpdatedAt   int64
}
