// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
	"github.com/moroz/go-altcha-video/internal/dbtypes"
)

type Comment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	Body      string
	Signature string
	Website   *string
	CreatedAt dbtypes.UnixTimestamp
	UpdatedAt dbtypes.UnixTimestamp
}

type Post struct {
	ID          uuid.UUID
	Author      string
	Title       string
	Body        string
	Slug        string
	PublishedAt *dbtypes.UnixTimestamp
	CreatedAt   dbtypes.UnixTimestamp
	UpdatedAt   dbtypes.UnixTimestamp
}
