// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package queries

import (
	"context"
)

const getPostBySlug = `-- name: GetPostBySlug :one
select id, author, title, body, slug, published_at, created_at, updated_at from posts
where slug = ?
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (*Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Body,
		&i.Slug,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPosts = `-- name: ListPosts :many
select id, author, title, body, slug, published_at, created_at, updated_at from posts
where published_at is not null
order by published_at desc
`

func (q *Queries) ListPosts(ctx context.Context) ([]*Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Body,
			&i.Slug,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
